### PR TITLE
Favicon Added

### LINKED ISSUE #1: BUG : Favicon should be added !!
Favicon should be added for a web page.

**Expected Behavior: **
The favicon should be added like this, 
after_favicon

**Actual Behavior: **
The favicon is not added, 
before_favicon

### PR DESCRIPTION
**Pull request by prashh-k**
resolved #1  
Favicon is added in a web page.

before_favicon

after_favicon

### CODE REVIEW

**Review by EternoSeeker — CHANGES_REQUESTED** [review]
Hello, just keep the favicon part, you are adding two features in single PR
spin png issue was fixed, so please look into it.

**Comment by prashh-k** [comment]
how should i undo the spin png feature please tell ?

**Comment by prashh-k** [comment]
done !

**Review by EternoSeeker — APPROVED** [review]

**Comment by prashh-k** [comment]
Thanks you 😊😊✨

**Pull request merged**
